
server.port=8083

jwt.secret=mySecretKey404E635266556A586E3272357538782F413F4428

## Auth / User management ? public login + user CRUD
#spring.cloud.gateway.routes[0].id=auth-service-route
#spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**
#
## Trial Protocol service
#spring.cloud.gateway.routes[1].id=trialprotocol-service-route
#spring.cloud.gateway.routes[1].uri=lb://trialprotocol-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/protocols/**
#
## Subject Enrollment service
#spring.cloud.gateway.routes[2].id=subject-enrollment-route
#spring.cloud.gateway.routes[2].uri=lb://SubjectEnrollment
#spring.cloud.gateway.routes[2].predicates[0]=Path=/api/subjects/**
#
## Visit Scheduling service
#spring.cloud.gateway.routes[3].id=visit-scheduling-route
#spring.cloud.gateway.routes[3].uri=lb://visit-scheduling
#spring.cloud.gateway.routes[3].predicates[0]=Path=/api/visits/**
#
## Adverse Event (Pharmacovigilance) service
#spring.cloud.gateway.routes[4].id=adverseevent-route
#spring.cloud.gateway.routes[4].uri=lb://adverseevent
#spring.cloud.gateway.routes[4].predicates[0]=Path=/api/events/**
#
## Lab Sample & IP Tracking service (CTDS)
#spring.cloud.gateway.routes[5].id=ctds-route
#spring.cloud.gateway.routes[5].uri=lb://ctds
#spring.cloud.gateway.routes[5].predicates[0]=Path=/api/samples,/api/samples/**,/api/inventory,/api/inventory/**
