spring.application.name=api-gateway
spring.config.import=optional:configserver:http://localhost:8888
# Fallback
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.registry-fetch-interval-seconds=5
jwt.secret=mySecretKey404E635266556A586E3272357538782F413F4428


# Load balancer retry
spring.cloud.loadbalancer.retry.enabled=true

# Global timeouts
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=30s

# Fallback routes (also defined in GatewayConfig.java and config-server)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/users/**

spring.cloud.gateway.routes[1].id=trialprotocol-service
spring.cloud.gateway.routes[1].uri=lb://trialprotocol-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/protocols/**

spring.cloud.gateway.routes[2].id=SubjectEnrollment
spring.cloud.gateway.routes[2].uri=lb://SubjectEnrollment
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/subjects/**

spring.cloud.gateway.routes[3].id=visit-scheduling
spring.cloud.gateway.routes[3].uri=lb://visit-scheduling
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/visits/**

spring.cloud.gateway.routes[4].id=adverseevent
spring.cloud.gateway.routes[4].uri=lb://adverseevent
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/events/**

spring.cloud.gateway.routes[5].id=labsampleandiptracking
spring.cloud.gateway.routes[5].uri=lb://labsampleandiptracking
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/samples,/api/samples/**,/api/inventory,/api/inventory/**

